/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.skrubb.blog_front_end;

import com.skrubb.blog_back_end.core.Author;
import com.skrubb.blog_back_end.core.Author.AccessLevel;
import javax.enterprise.context.RequestScoped;
import javax.faces.bean.ManagedBean;
import javax.inject.Inject;
import javax.inject.Named;
import javax.validation.constraints.Digits;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 *
 * @author hajo
 */

@ManagedBean(name="addAuthor")  // NOTE enterprise package, else disaster!!!
public class AddAuthorBB {

    @NotNull(message="{common.notEmpty}")
    @Size(min=4, max=20, message="{author.name}")
    private String name;
    
    @NotNull(message="{common.notEmpty}")
    @Size(min=4, max=20, message="{author.name}")
    private String password;
    
    @NotNull(message="{common.notEmpty}")
    private AccessLevel al;

    public String save() {
        // Id generated by database
        
        Author a = new Author(name, password, al);
        DummyDB.authors.add(a);

        return "manage_authors";
    }
    
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }
    
   public AccessLevel getAL() {
        return al;
    }

    public void setAL(AccessLevel al) {
        this.al = al;
    }
    
}
